apiVersion: v1
kind: Pod
metadata:
  name: big-corp-app1
spec:
  containers:
  - name: busybox1
    image: busybox
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  volumes:
  - name: varlog
    emptyDir: {}
