apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    role: multipod
spec:
  containers:
    - name: alpha
      image: nginx
      env:
      - name: name
        value: alpha
    - name: beta
      image: busybox
      env:
      - name: name
        value: beta
      command: ["sleep","4800"] 
