apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: nginx
    name: alpha
  - image: busybox
    name: beta
    command: ['sleep','4800']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
