apiVersion: v1
kind: Pod
metadata:
 name: non-persistent-redis
 namespace: qa
spec:
 containers:
 - name: redis
   image: redis
   volumeMounts:
   - mountPath: "/data/redis"
     name: app-cache
 volumes:
 - name: app-cache
   emptyDir: {}
