apiVersion: v1
kind: Pod
metadata:
 name: prod-redis
spec:
 containers:
 - name: prod-redis
   image: redis:alpine
 tolerations:
 - key: "env_type"
   operator: "Equal"
   value: "production"
   effect: "NoSchedule"
