apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv10
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: csi-hostpath-sc
  hostPath:
   path: "/opt/srv"
