apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-cache
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/srv/dataredis"
