apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  containers:
  - name: test2
    image: redis
    env:
      - name: CREDENTIALS
        valueFrom:
          secretKeyRef:
            name: super-secret1
            key: password
