apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: test1
    image: redis
    volumeMounts:
    - name: secretvol
      mountPath: "/secrets"
      readOnly: true
  volumes:
  - name: secretvol
    secret:
      secretName: super-secret1
