apiVersion: v1
kind: Pod
metadata:
 name: super-user-pod1
spec:
 containers:
 - name: super-user-pod1
   image: busybox:1.28
   command: ["sleep","4800"]
   securityContext:
    capabilities:
     add: ["SYS_TIME"]
