apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: test-pod
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-pvc
