apiVersion: v1
kind: Pod
metadata:
  name: testsecret2
spec:
  containers:
  - name: testsecret2
    image: redis
    env:
      - name: CREDENTIALS
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: password
