apiVersion: v1
kind: Pod
metadata:
  name: testsecret
spec:
  containers:
  - name: testsecret
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/secret"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: test-secret
