apiVersion: v1
kind: Pod
metadata:
 name: test2
spec:
 containers:
 - name: test2
   image: redis
   env:
    - name: SECRET_PASSWORD
      valueFrom:
       secretKeyRef:
        name: super-secret
        key: password
